name: clean-database

on:
  workflow_dispatch:
  schedule:
   - cron: '0 11 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'paladins-stats-db'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        registry-url: "https://npm.pkg.github.com"

    - name: Install Dependencies
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and run script
      run: npm run clean-database
      env:
        DEV_ID: ${{ secrets.DEV_ID }}
        AUTH_KEY: ${{ secrets.AUTH_KEY }}
        PALADINS_STATS_DB_URI: ${{ secrets.PALADINS_STATS_DB_URI }}
        PALADINS_STATS_DB_NAME: ${{ secrets.PALADINS_STATS_DB_NAME }}
